acme_blog_page:
    type: rest
    prefix: /v1
    resource: Acme\BlogBundle\Controller\PageController
    name_prefix:  api_1_ # naming collision
    
acme_blog_usuario:
    type: rest
    prefix: /aspe
    resource: Acme\BlogBundle\Controller\UsuarioController
    name_prefix:  aspe_
    
acme_blog_perfil:
    type: rest
    prefix: /aspe
    resource: Acme\BlogBundle\Controller\PerfilController
    name_prefix:  aspe_
    
acme_blog_curso:
    type: rest
    prefix: /aspe
    resource: Acme\BlogBundle\Controller\CursoController
    name_prefix:  aspe_
    
acme_blog_disciplina:
    type: rest
    prefix: /aspe
    resource: Acme\BlogBundle\Controller\DisciplinaController
    name_prefix:  aspe_

acme_blog_topico:
    type: rest
    prefix: /aspe
    resource: Acme\BlogBundle\Controller\TopicoController
    name_prefix:  aspe_
    
acme_blog_ementa:
    type: rest
    prefix: /aspe
    resource: Acme\BlogBundle\Controller\EmentaController
    name_prefix:  aspe_